name: CI/CD with Docker and Render Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-weather-app:latest
          build-args: # Pass secrets as build arguments
            FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
            API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}

  # deploy-to-render:
  #   name: Deploy to Render
  #   runs-on: ubuntu-latest
  #   needs: build-and-push

  #   steps:
  #     # Checkout the repository
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     # Deploy to Render
  #     - name: Deploy to Render
  #       env:
  #         RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
  #       run: |
  #         curl -X POST \
  #           -H "Authorization: Bearer $RENDER_API_KEY" \
  #           -H "Content-Type: application/json" \
  #           -d '{"serviceId": "your-service-id", "clearCache": false}' \
  #           https://api.render.com/v1/services/your-service-id/deploys
